I HAS A FUCK$
I HAS A THIS$
I HAS A SHIT$
I HAS A SPACE$
HAI
    CAN HAS STDIO?
*   CAN HAZ COPYBOOK?
    LOL FUCK R "FUCK"
    LOL THIS R "THIS"
    LOL SHIT R "SHIT"
    LOL SPACE R " "
    VISIBLE FUCK
    VISIBLE SPACE
    VISIBLE THIS
    VISIBLE SPACE
    VISIBLE! SHIT
KTHXBYE
