I HAS A FUCK$
I HAS A THIS$
I HAS A SHIT$
HAI
        CAN HAS STDIO?
*       CAN HAZ COPYBOOK?
        LOL FUCK R "FUCK"
        LOL THIS R "THIS"
        LOL SHIT R "SHIT"
        VISIBLE FUCK
        VISIBLE THIS
        VISIBLE! SHIT
KTHXBB
